version: '3.6'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 5001:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./entry:/docker-entrypoint-initdb.d
      - ./data:/data/db

volumes:
  data: